/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controlpedidosevaluacion3;

/**
 *
 * @author USUARIO
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbPlato = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPedido = new javax.swing.JTextArea();
        chkAgranda = new javax.swing.JCheckBox();
        chkEnsalada = new javax.swing.JCheckBox();
        chkPostre = new javax.swing.JCheckBox();
        chkJuguete = new javax.swing.JCheckBox();
        chkDelivery = new javax.swing.JCheckBox();
        btnProcesar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Control de Pedidos");

        jLabel2.setText("Restaurante de comida rapida \"Los Patrones\"");

        jLabel3.setText("Plato");

        cmbPlato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hamburguesa Peruana", "Big Box", "Banquete Personal", "Enchilada Venezolana", "Especial 4 Estaciones" }));

        jLabel4.setText("Complementos");

        jLabel5.setText("Pedido:");

        txtPedido.setColumns(20);
        txtPedido.setRows(5);
        jScrollPane1.setViewportView(txtPedido);

        chkAgranda.setText("Agranda tu combo");

        chkEnsalada.setText("Ensalada Extra");

        chkPostre.setText("Postre");

        chkJuguete.setText("Juguete promocion");

        chkDelivery.setText("Delivery");

        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cmbPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(chkAgranda)
                            .addComponent(chkEnsalada)
                            .addComponent(chkPostre)
                            .addComponent(chkJuguete)
                            .addComponent(chkDelivery)
                            .addComponent(btnProcesar))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkAgranda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkEnsalada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkPostre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkJuguete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkDelivery)
                        .addGap(18, 18, 18)
                        .addComponent(btnProcesar)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        // TODO add your handling code here:
        Plato plato = null;
        
        //COMBO BOX
        if(cmbPlato.getSelectedItem().equals("Hamburguesa Peruana")){
            PlatoFactory platoFactory = new PlatoFactory();
            plato = platoFactory.generarPedido(1);
        }
        if(cmbPlato.getSelectedItem().equals("Big Box")){
            PlatoFactory platoFactory = new PlatoFactory();
            plato = platoFactory.generarPedido(2);
        }
        if(cmbPlato.getSelectedItem().equals("Banquete Personal")){
            PlatoFactory platoFactory = new PlatoFactory();
            plato = platoFactory.generarPedido(3);
        }
        if(cmbPlato.getSelectedItem().equals("Enchilada Venezolana")){
            PlatoFactory platoFactory = new PlatoFactory();
            plato = platoFactory.generarPedido(4);
        }
        if(cmbPlato.getSelectedItem().equals("Especial 4 Estaciones")){
            PlatoFactory platoFactory = new PlatoFactory();
            plato = platoFactory.generarPedido(5);
        }
        
        float precioPedido=plato.getPrecioPlato();
        
        //CHECKS
        if(chkAgranda.isSelected()){
            plato = new Agranda(plato);
            precioPedido += 2;
        }
        if(chkEnsalada.isSelected()){
            plato = new Ensalada(plato);
            precioPedido += 2;
        }
        if(chkPostre.isSelected()){
            plato = new Postre(plato);
            precioPedido += 2;
        }
        if(chkJuguete.isSelected()){
            plato = new Juguete(plato);
            precioPedido += 2;
        }
        if(chkDelivery.isSelected()){
            plato = new Delivery(plato);
            precioPedido += 2;
        }
       
        String textoPrincipal = plato.getDetallePlato();
        textoPrincipal += "\n\n";
        textoPrincipal += "*************";
        textoPrincipal += "TOTAL A PAGAR: S/."+precioPedido;
        txtPedido.setText(textoPrincipal);
        
    }//GEN-LAST:event_btnProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcesar;
    private javax.swing.JCheckBox chkAgranda;
    private javax.swing.JCheckBox chkDelivery;
    private javax.swing.JCheckBox chkEnsalada;
    private javax.swing.JCheckBox chkJuguete;
    private javax.swing.JCheckBox chkPostre;
    private javax.swing.JComboBox<String> cmbPlato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtPedido;
    // End of variables declaration//GEN-END:variables
}
